tot_len: 719

sim_num: 98
moment_scheme: 2
batch_size: 256 
beta: 0.35
learning_rate: 2e-4

act: torch.nn.ReLU()
loss_func: null

n_layers: 5
ns: 200
out_features: 4
depth: 9
p: 0.25
norm: Standard_Norm
inputs_mean: null
inputs_std: null
loss_absolute: True
mass_cons_loss: True
multi_step: True
step_size: 2

max_epochs: 1