data_dir: /gpfs/work/sharmas/mc-snow-data/single_sim_data
tot_len: 1

sim_num: 9078
avg_dataloader: True
single_sim_num: 0
moment_scheme: 2
batch_size: 256 
beta: 0.35
learning_rate: 2e-4

act: torch.nn.ReLU()
loss_func: null

n_layers: 3
ns: 200

depth: 9
p: 0.25
norm: Standard_Norm
inputs_mean: null
inputs_std: null
loss_absolute: True
mass_cons_moments: True
mass_cons_updates: True
hard_constraints_moments: False
hard_constraints_updates: False
multi_step: False
step_size: 1

max_epochs: 5000
use_batch_norm: False
use_dropout: False